# Generated by Django 5.2.10 on 2026-01-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_name", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="article_covers/",
                verbose_name="封面图",
            ),
        ),
    ]
