# Generated by Django 5.2.9 on 2026-02-20 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0003_calendarevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=20, verbose_name='招生省份')),
                ('subject_type', models.CharField(choices=[('理科', '理科'), ('文科', '文科')], max_length=10, verbose_name='科类')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('min_score', models.IntegerField(verbose_name='最低投档分')),
                ('avg_score', models.IntegerField(blank=True, null=True, verbose_name='平均分')),
                ('max_score', models.IntegerField(blank=True, null=True, verbose_name='最高分')),
                ('ranking', models.IntegerField(blank=True, help_text='全省排名', null=True, verbose_name='最低位次')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '录取分数线',
                'verbose_name_plural': '录取分数线',
                'ordering': ['-year', '-min_score'],
            },
        ),
        migrations.CreateModel(
            name='CollegePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_order', models.IntegerField(help_text='1-6，1为第一志愿', verbose_name='志愿顺序')),
                ('is_adjusted', models.BooleanField(default=False, verbose_name='是否服从调剂')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '志愿填报',
                'verbose_name_plural': '志愿填报',
                'ordering': ['preference_order'],
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='专业名称')),
                ('category', models.CharField(choices=[('工学', '工学'), ('理学', '理学'), ('文学', '文学'), ('历史学', '历史学'), ('哲学', '哲学'), ('经济学', '经济学'), ('管理学', '管理学'), ('法学', '法学'), ('教育学', '教育学'), ('艺术学', '艺术学'), ('医学', '医学'), ('农学', '农学')], max_length=50, verbose_name='专业类别')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='专业代码')),
                ('description', models.TextField(blank=True, verbose_name='专业介绍')),
                ('employment_rate', models.DecimalField(blank=True, decimal_places=2, help_text='百分比', max_digits=5, null=True, verbose_name='就业率')),
                ('salary_range', models.CharField(blank=True, max_length=50, verbose_name='薪资范围')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '专业信息',
                'verbose_name_plural': '专业信息',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('province', models.CharField(max_length=20, verbose_name='省份')),
                ('total_score', models.IntegerField(help_text='高考总分', verbose_name='总分')),
                ('chinese_score', models.IntegerField(blank=True, null=True, verbose_name='语文')),
                ('math_score', models.IntegerField(blank=True, null=True, verbose_name='数学')),
                ('english_score', models.IntegerField(blank=True, null=True, verbose_name='英语')),
                ('comprehensive_score', models.IntegerField(blank=True, null=True, verbose_name='综合')),
                ('subject_type', models.CharField(choices=[('理科', '理科'), ('文科', '文科')], default='理科', max_length=10, verbose_name='科类')),
                ('year', models.IntegerField(default=2024, verbose_name='高考年份')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '学生档案',
                'verbose_name_plural': '学生档案',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='大学名称')),
                ('province', models.CharField(max_length=20, verbose_name='所在省份')),
                ('city', models.CharField(blank=True, max_length=20, verbose_name='所在城市')),
                ('university_type', models.CharField(choices=[('985', '985工程'), ('211', '211工程'), ('双一流', '双一流'), ('普通本科', '普通本科'), ('专科', '专科')], default='普通本科', max_length=20, verbose_name='办学类型')),
                ('level', models.CharField(choices=[('本科', '本科'), ('专科', '专科')], default='本科', max_length=20, verbose_name='办学层次')),
                ('ranking', models.IntegerField(blank=True, help_text='软科排名', null=True, verbose_name='全国排名')),
                ('description', models.TextField(blank=True, verbose_name='学校简介')),
                ('website', models.URLField(blank=True, verbose_name='官网')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='university_logos/', verbose_name='校徽')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '大学信息',
                'verbose_name_plural': '大学信息',
                'ordering': ['ranking'],
            },
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.AddField(
            model_name='collegepreference',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_name.major', verbose_name='专业'),
        ),
        migrations.AddField(
            model_name='admissionscore',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_name.major', verbose_name='专业'),
        ),
        migrations.AddField(
            model_name='collegepreference',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_name.studentprofile', verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='collegepreference',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_name.university', verbose_name='大学'),
        ),
        migrations.AddField(
            model_name='admissionscore',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_name.university', verbose_name='大学'),
        ),
        migrations.DeleteModel(
            name='CalendarEvent',
        ),
    ]
