# Generated by Django 5.2.9 on 2026-02-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0004_admissionscore_collegepreference_major_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionscore',
            name='subject_type',
            field=models.CharField(choices=[('物理类', '物理类'), ('历史类', '历史类')], max_length=10, verbose_name='科类'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='subject_type',
            field=models.CharField(choices=[('物理类', '物理类'), ('历史类', '历史类')], default='物理类', max_length=10, verbose_name='科类'),
        ),
    ]
